export {default as adjustText1} from '../Home/images/img/adjustText.jpeg'
// export {default as asphaltNine} from './img/asphalt9.jpeg'
export {default as avatar} from './images/img/avatar.jpeg'
export {default as cogo} from './images/img/co-go.jpeg'
export {default as first} from './images/img/first.jpg'
export {default as fortnite} from './images/img/fortnite.jpeg'
export {default as gta} from './images/img/gta.jpeg'
export {default as playerProfile} from './images/img/playerProfile.webp'
export {default as pubg} from './images/img/pubg.jpeg'
export {default as Sample} from './images/img/Sample.webp'
export {default as Second} from './images/img/Second.jpeg'
export {default as Valorant} from './images/img/valorant.jpeg'
export {default as warcraft} from './images/img/warcraft.jpg'
export {default as warface } from './images/img/warface.jpeg'


// export {default as title} from './png/title_logo.png'
export {default as asphaltNine} from './images/img/asphalt9.jpeg' 
// export {default as Valorant} from './images/img/valorant.jpeg'
export {default as title} from './images/png/title_logo.png'
export {default as High} from './videos/HighContrastMode.mp4'
export {default as home } from './videos/homeBackground.webm'
export {default as Keyboard} from './videos/KeyboardNavigation.mp4'
export {default as screen} from './videos/screenreaderAccebility.mp4'
export {default as clickbutton} from './audio/clickbutton.mp3'

